# Generated by Django 4.2 on 2024-05-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prodinv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_adding',
            name='product_price',
            field=models.FloatField(default=0.0),
        ),
    ]
